name: gefion

plugins:
  - name: solidity
  - name: vyper
  - name: hardhat
  - name: etherscan
  - name: polygon
  - name: bsc
  - name: infura

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    ref: v4.9.5
  - name: tokenized-strategy
    github: gefion-labs/tokenized-strategy
    ref: v1.0.0
    contracts_folder: src

solidity:
  version: 0.8.18
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.9.5"
    - "@tokenized-strategy=tokenized-strategy/v1.0.0"

ethereum:
  local:
    default_provider: hardhat
  sepolia:
    transaction_acceptance_timeout: 600
    